import { Prompt } from '@/types/prompt';

export const MOCK_PROMPTS: Prompt[] = [
  {
    id: 'prompt-001',
    name: '文章要約プロンプト',
    description: '長文テキストを指定された文字数で簡潔に要約するプロンプト。主要なポイントを保持しつつ圧縮します。',
    content: '以下のテキストを{{文字数}}文字以内で要約してください。主要なポイントを漏らさず、簡潔にまとめてください。\n\n{{テキスト}}',
    modelId: 'gpt-4o',
    status: 'published',
    latestVersion: 5,
    createdAt: '2026-03-01T09:00:00Z',
    updatedAt: '2026-04-15T14:30:00Z',
    createdBy: '山田太郎',
  },
  {
    id: 'prompt-002',
    name: 'コードレビュープロンプト',
    description: 'ソースコードの品質・セキュリティ・パフォーマンスを多角的にレビューするプロンプト。',
    content: '以下の{{言語}}コードをレビューしてください。\n\n観点:\n- バグの有無\n- セキュリティリスク\n- パフォーマンスの改善点\n- 可読性・保守性\n\n```{{言語}}\n{{コード}}\n```',
    modelId: 'claude-3-5-sonnet',
    status: 'published',
    latestVersion: 3,
    createdAt: '2026-03-05T10:00:00Z',
    updatedAt: '2026-04-12T11:20:00Z',
    createdBy: '鈴木花子',
  },
  {
    id: 'prompt-003',
    name: 'メール文面生成プロンプト',
    description: 'ビジネスメールの文面を目的・トーンに応じて自動生成するプロンプト。',
    content: '以下の条件でビジネスメールの文面を作成してください。\n\n目的: {{目的}}\n宛先: {{宛先}}\nトーン: {{トーン}}\n\n補足情報:\n{{補足}}',
    modelId: 'gpt-4o-mini',
    status: 'published',
    latestVersion: 2,
    createdAt: '2026-03-10T08:00:00Z',
    updatedAt: '2026-04-10T16:45:00Z',
    createdBy: '山田太郎',
  },
  {
    id: 'prompt-004',
    name: '翻訳品質チェックプロンプト',
    description: '翻訳された文章の正確性・自然さを評価し、改善点を提示するプロンプト。',
    content: '以下の翻訳を評価してください。\n\n原文（{{原文言語}}）:\n{{原文}}\n\n翻訳文（{{翻訳言語}}）:\n{{翻訳文}}\n\n以下の観点で評価してください:\n1. 正確性\n2. 自然さ\n3. 用語の一貫性\n4. 改善提案',
    modelId: 'claude-3-opus',
    status: 'draft',
    latestVersion: 1,
    createdAt: '2026-04-01T13:00:00Z',
    updatedAt: '2026-04-01T13:00:00Z',
    createdBy: '佐藤次郎',
  },
  {
    id: 'prompt-005',
    name: 'ユーザーストーリー生成プロンプト',
    description: '要件からアジャイル開発向けのユーザーストーリーを自動生成するプロンプト。',
    content: '以下の要件をもとに、アジャイル開発で使用するユーザーストーリーを生成してください。\n\nフォーマット: 「{{ペルソナ}}として、{{機能}}をしたい。なぜなら{{理由}}だからだ。」\n\n要件:\n{{要件}}',
    modelId: 'gpt-4o',
    status: 'published',
    latestVersion: 4,
    createdAt: '2026-03-15T11:00:00Z',
    updatedAt: '2026-04-18T09:15:00Z',
    createdBy: '鈴木花子',
  },
  {
    id: 'prompt-006',
    name: 'テストケース生成プロンプト',
    description: '仕様書からテストケースを網羅的に自動生成するプロンプト。境界値やエッジケースもカバーします。',
    content: '以下の仕様に基づいてテストケースを生成してください。\n\n仕様:\n{{仕様}}\n\n以下を含めてください:\n- 正常系テスト\n- 異常系テスト\n- 境界値テスト\n- エッジケース',
    modelId: 'gemini-1.5-pro',
    status: 'draft',
    latestVersion: 1,
    createdAt: '2026-04-10T15:30:00Z',
    updatedAt: '2026-04-10T15:30:00Z',
    createdBy: '佐藤次郎',
  },
  {
    id: 'prompt-007',
    name: 'FAQ生成プロンプト',
    description: '製品・サービスのドキュメントからFAQを自動生成するプロンプト。',
    content: '以下のドキュメントから、ユーザーがよく質問しそうなFAQ（よくある質問と回答）を{{件数}}件生成してください。\n\nドキュメント:\n{{ドキュメント}}',
    modelId: 'gpt-4o-mini',
    status: 'archived',
    latestVersion: 6,
    createdAt: '2026-02-20T10:00:00Z',
    updatedAt: '2026-03-30T12:00:00Z',
    createdBy: '山田太郎',
  },
];
